/**
 * @description       : 
 * @author            : hugodhm@icloud.com
 * @group             : 
 * @last modified on  : 08-16-2021
 * @last modified by  : hugodhm@icloud.com
**/
public with sharing class MainTriggerOnAccount extends TriggerHandler{
    public MainTriggerOnAccount() {
        System.debug('Starting controller');
    }

    public override void beforeInsert() {
        //....
    }
    public override void afterInsert() {
        //.....
    }
}
